### ISSUE TITLE
Second-Level Domains

### ISSUE THREAD

**Issue by cevatbarisyilmaz** [jbenet/go-is-domain#14]
Some TLDs (mostly ccTLDs I guess) use second-level domains. For example "co.uk" and "com.tr" are not full domain names (but isdomain will return true).

It would be nice to handle these cases, though I was not able to find a list or document on this.

**Comment by lidel** [comment]
@cevatbarisyilmaz I don't think those need any special handling as long the very last label is whitelisted, both examples your provided should work:

https://github.com/jbenet/go-is-domain/blob/009bc9fc8d69261cc21e8eb2aa0925af155d1c11/tlds_iana.go#L1275

https://github.com/jbenet/go-is-domain/blob/009bc9fc8d69261cc21e8eb2aa0925af155d1c11/tlds_iana.go#L1251

Mind confirming and closing this?

**Comment by cevatbarisyilmaz** [comment]
I'm not sure about the exact scope or aim of this project, so feel free to close this issue if I got it wrong. My point was about false positives rather than false negatives. I don't know about the exceptions but without a third-level domain name, ccSLDs are not registerable domain names. For example entering 'co.uk' in Chrome ends up as a Google search rather than a connection attempt to 'co.uk'.

**Comment by lidel** [comment]
Ah, yes. That is not in scope of this package. 

There is public list maintained at   https://publicsuffix.org/ - it is used by browsers to tell which suffix is interpreted as defacto "tld".

**Comment by cevatbarisyilmaz** [comment]
Thanks!
