### ISSUE TITLE
Transfer to ipfs org?

### ISSUE THREAD

**Issue by lidel** [jbenet/go-is-domain#16]
@Stebalien / @jbenet thoughts on moving this package to `ipfs` org on github?
It is pretty core lib: used by namesys in go-ipfs for DNSLink support, and having it under ipfs org would reduce increase bus factor.

**Comment by lidel** [comment]
cc @aschmahmann

**Comment by aschmahmann** [comment]
Seems fine by me, although given the status of the linked issue maybe go-ipfs just doesn't need this repo at all?

**Comment by lidel** [comment]
I agree, go-ipfs should not care about "legitimacy" of any TLD. 
Let's continue in https://github.com/ipfs/go-ipfs/pull/7902
