### ISSUE TITLE
 Not compatible with Punycode

### ISSUE THREAD

**Issue by ivan386** [jbenet/go-is-domain#7]
> [Punycode](https://en.wikipedia.org/wiki/Punycode) is a way to represent Unicode with the limited character subset of ASCII supported by the Domain Name System. For example, "München" (German name for the city of Munich) would be encoded as "Mnchen-3ya".

Punycode is denoted by the prefix in domain name "xn--". For example "xn--e1afmkfd.xn--80akhbyknj4f" is punycoded domain name "пример.испытание". 

"xn----itbbluqhd8e0d.xn--80akhbyknj4f" is "ещё-пример.испытание"

**Comment by ivan386** [comment]
So maybe its time to accept bug fix?

**Comment by Stebalien** [comment]
Fixed (finally...)
